import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useChainInfo } from '@goudchain/hooks';
import { Card, CardHeader, CardTitle, CardContent, Spinner } from '@goudchain/ui';
import { formatHash, formatRelativeTime } from '@goudchain/utils';
import { SpinnerSize } from '@goudchain/types';
export default function ExplorerPage() {
    const { data: chainInfo, isLoading } = useChainInfo();
    if (isLoading) {
        return (_jsx("div", { className: "flex items-center justify-center h-64", children: _jsx(Spinner, { size: SpinnerSize.Large }) }));
    }
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-3xl font-bold text-white mb-2", children: "Blockchain Explorer" }), _jsx("p", { className: "text-zinc-500", children: "Explore blocks and chain data" })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Chain Information" }) }), _jsx(CardContent, { className: "space-y-4", children: _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-zinc-400", children: "Chain Length" }), _jsx("p", { className: "text-2xl font-bold text-white font-mono", children: chainInfo?.chain_length ?? 0 })] }), _jsxs("div", { children: [_jsx("p", { className: "text-sm text-zinc-400", children: "Pending Data" }), _jsx("p", { className: "text-2xl font-bold text-white font-mono", children: chainInfo?.pending_data_count ?? 0 })] })] }) })] }), chainInfo?.latest_block && (_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Latest Block" }) }), _jsx(CardContent, { children: _jsxs("div", { className: "space-y-3 font-mono text-sm", children: [_jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-zinc-400", children: "Block Number" }), _jsx("p", { className: "text-white", children: chainInfo.latest_block.block_number })] }), _jsxs("div", { children: [_jsx("p", { className: "text-zinc-400", children: "Timestamp" }), _jsx("p", { className: "text-white", children: formatRelativeTime(chainInfo.latest_block.timestamp) })] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-zinc-400", children: "Previous Hash" }), _jsx("code", { className: "block p-2 bg-zinc-900 rounded text-xs break-all text-white", children: formatHash(chainInfo.latest_block.previous_hash, 16) })] }), _jsxs("div", { children: [_jsx("p", { className: "text-zinc-400", children: "Merkle Root" }), _jsx("code", { className: "block p-2 bg-zinc-900 rounded text-xs break-all text-white", children: formatHash(chainInfo.latest_block.merkle_root, 16) })] }), _jsxs("div", { children: [_jsx("p", { className: "text-zinc-400", children: "Validator" }), _jsx("code", { className: "block p-2 bg-zinc-900 rounded text-xs break-all text-white", children: formatHash(chainInfo.latest_block.validator, 16) })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-zinc-400", children: "Data Count" }), _jsx("p", { className: "text-white", children: chainInfo.latest_block.data_count })] }), _jsxs("div", { children: [_jsx("p", { className: "text-zinc-400", children: "Signature" }), _jsx("code", { className: "text-xs text-white", children: formatHash(chainInfo.latest_block.signature, 12) })] })] })] }) })] }))] }));
}
//# sourceMappingURL=explorer.js.map