import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMetrics } from '@goudchain/hooks';
import { Card, CardHeader, CardTitle, CardContent, Spinner } from '@goudchain/ui';
import { formatNumber, formatDate } from '@goudchain/utils';
import { SpinnerSize } from '@goudchain/types';
export default function MetricsPage() {
    const { data, isLoading } = useMetrics();
    if (isLoading) {
        return (_jsx("div", { className: "flex items-center justify-center h-64", children: _jsx(Spinner, { size: SpinnerSize.Large }) }));
    }
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-3xl font-bold text-white mb-2", children: "System Metrics" }), _jsx("p", { className: "text-zinc-500", children: "Real-time system performance metrics" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6", children: [_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { className: "text-sm text-zinc-400", children: "Chain Length" }) }), _jsx(CardContent, { children: _jsx("p", { className: "text-3xl font-bold text-white font-mono", children: formatNumber(data?.chain.length ?? 0) }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { className: "text-sm text-zinc-400", children: "Peer Count" }) }), _jsx(CardContent, { children: _jsx("p", { className: "text-3xl font-bold text-white font-mono", children: formatNumber(data?.network.peer_count ?? 0) }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { className: "text-sm text-zinc-400", children: "Operations Total" }) }), _jsx(CardContent, { children: _jsx("p", { className: "text-3xl font-bold text-white font-mono", children: formatNumber(data?.performance.operations_total ?? 0) }) })] })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Performance Metrics" }) }), _jsx(CardContent, { className: "space-y-4", children: _jsxs("div", { children: [_jsxs("div", { className: "flex justify-between mb-2", children: [_jsx("span", { className: "text-sm text-zinc-400", children: "Cache Hit Rate" }), _jsxs("span", { className: "text-sm font-mono text-white", children: [((data?.performance.cache_hit_rate ?? 0) * 100).toFixed(2), "%"] })] }), _jsx("div", { className: "w-full bg-zinc-800 rounded-full h-2", children: _jsx("div", { className: "bg-green-500 h-2 rounded-full", style: { width: `${(data?.performance.cache_hit_rate ?? 0) * 100}%` } }) })] }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Latest Block Information" }) }), _jsxs(CardContent, { className: "space-y-2 font-mono text-sm", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-zinc-400", children: "Block Number:" }), _jsx("span", { className: "text-white", children: data?.chain.latest_block_number ?? 0 })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-zinc-400", children: "Block Timestamp:" }), _jsx("span", { className: "text-white", children: data?.chain.latest_block_timestamp
                                            ? formatDate(data.chain.latest_block_timestamp)
                                            : 'N/A' })] })] })] })] }));
}
//# sourceMappingURL=metrics.js.map