# Development override for hot reload
# SPACE OPTIMIZATION: Shares target/ and cargo cache across all nodes via bind mounts
# This eliminates 3x duplication (saves ~15GB) while maintaining hot reload functionality
#
# DASHBOARD IN DEV MODE:
# The dashboard container is DISABLED in dev mode. Run the React app locally for hot reload:
#   cd web && pnpm dev
# This starts Vite dev server on localhost:3000 with instant hot reload.
services:

  node1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - shared_cargo_cache:/usr/local/cargo/registry
      - ./target:/app/target
      - node1_data:/data

  node2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - shared_cargo_cache:/usr/local/cargo/registry
      - ./target:/app/target

  node3:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - shared_cargo_cache:/usr/local/cargo/registry
      - ./target:/app/target
      - node3_data:/data

  jupyter:
    volumes:
      # Override with read-write for development (still git-tracked but editable)
      - ./python/notebooks:/home/jovyan/work/notebooks:rw

volumes:
  shared_cargo_cache:
  node1_data:
  node2_data:
  node3_data:
