# Development override for hot reload with RELEASE builds
# This provides production-like performance in dev mode
# Trade-off: Slower rebuilds but fast runtime
# SPACE OPTIMIZATION: Shares target/ and cargo cache across all nodes via bind mounts
# This eliminates 3x duplication (saves ~15GB) while maintaining hot reload functionality
services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile.dev-perf
    volumes:
      - ./src:/app/src
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - shared_cargo_cache:/usr/local/cargo/registry
      - ./target:/app/target

  node2:
    build:
      context: .
      dockerfile: Dockerfile.dev-perf
    volumes:
      - ./src:/app/src
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - shared_cargo_cache:/usr/local/cargo/registry
      - ./target:/app/target

  node3:
    build:
      context: .
      dockerfile: Dockerfile.dev-perf
    volumes:
      - ./src:/app/src
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - shared_cargo_cache:/usr/local/cargo/registry
      - ./target:/app/target

volumes:
  shared_cargo_cache:
