name: E2E Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'web/**'
      - '.github/workflows/e2e-tests.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'web/**'
      - '.github/workflows/e2e-tests.yml'
  workflow_dispatch:

jobs:
  e2e-tests:
    name: E2E Tests (${{ matrix.browser }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Start Docker Compose services
        run: |
          docker-compose -f docker-compose.local.yml up -d
          echo "Waiting for services to be healthy..."
          sleep 30
      
      - name: Wait for backend health
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8080/health; then
              echo "Backend is healthy"
              break
            fi
            echo "Waiting for backend... ($i/30)"
            sleep 2
          done
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        working-directory: web
        run: pnpm install --frozen-lockfile
      
      - name: Build dashboard
        working-directory: web
        run: pnpm build
      
      - name: Start dashboard dev server
        working-directory: web/apps/dashboard
        run: |
          pnpm dev &
          echo $! > dashboard.pid
          echo "Waiting for dashboard to start..."
          for i in {1..30}; do
            if curl -f http://localhost:3000; then
              echo "Dashboard is ready"
              break
            fi
            echo "Waiting for dashboard... ($i/30)"
            sleep 2
          done
      
      - name: Install Playwright browsers
        working-directory: web
        run: pnpm exec playwright install --with-deps ${{ matrix.browser }}
      
      - name: Run E2E tests
        working-directory: web
        run: pnpm test:e2e --project=${{ matrix.browser }}
        env:
          CI: true
          DASHBOARD_URL: http://localhost:3000
          API_URL: http://localhost:8080
          WS_URL: ws://localhost:8080/ws
      
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: web/playwright-report/
          retention-days: 30
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results-${{ matrix.browser }}
          path: web/test-results/
          retention-days: 30
      
      - name: Stop dashboard
        if: always()
        working-directory: web/apps/dashboard
        run: |
          if [ -f dashboard.pid ]; then
            kill $(cat dashboard.pid) || true
            rm dashboard.pid
          fi
      
      - name: Stop Docker Compose services
        if: always()
        run: docker-compose -f docker-compose.local.yml down -v
      
      - name: Collect Docker logs
        if: failure()
        run: docker-compose -f docker-compose.local.yml logs > docker-logs.txt
      
      - name: Upload Docker logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs-${{ matrix.browser }}
          path: docker-logs.txt
          retention-days: 7
  
  visual-regression:
    name: Visual Regression Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Install dependencies
        working-directory: web
        run: pnpm install --frozen-lockfile
      
      - name: Build Storybook
        working-directory: web/packages/ui
        run: pnpm build-storybook
      
      - name: Start Storybook server
        working-directory: web/packages/ui
        run: |
          npx http-server storybook-static -p 6006 &
          echo $! > storybook.pid
          sleep 5
      
      - name: Install Playwright browsers
        working-directory: web
        run: pnpm exec playwright install --with-deps chromium
      
      - name: Run visual regression tests
        working-directory: web
        run: pnpm test:e2e:visual
        env:
          CI: true
          STORYBOOK_URL: http://localhost:6006
          VISUAL_THRESHOLD: 0.1
      
      - name: Upload visual regression artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-regression-report
          path: |
            web/playwright-report/
            web/e2e/visual/actual/
            web/e2e/visual/diff/
          retention-days: 30
      
      - name: Stop Storybook
        if: always()
        working-directory: web/packages/ui
        run: |
          if [ -f storybook.pid ]; then
            kill $(cat storybook.pid) || true
            rm storybook.pid
          fi

  test-report:
    name: Publish Test Report
    runs-on: ubuntu-latest
    needs: [e2e-tests, visual-regression]
    if: always()
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      
      - name: Generate combined report
        run: |
          echo "# E2E Test Results" > test-summary.md
          echo "" >> test-summary.md
          echo "## Test Execution Summary" >> test-summary.md
          echo "- Browser Tests: Chromium, Firefox, WebKit" >> test-summary.md
          echo "- Visual Regression: Completed" >> test-summary.md
          echo "" >> test-summary.md
          echo "See artifacts for detailed reports." >> test-summary.md
      
      - name: Upload test summary
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: test-summary.md
          retention-days: 30
